### ISSUE TITLE
Four suggestions

### ISSUE THREAD

**Issue by HiTyra** [kth1207/Project#1]
Hi Tony,

Firstly, I really like the idea of your site! I think its really creative that you plan on adding the Korean restaurants near you section and how you imbedded related cooking Youtube videos. The menu dropdown menu is also cool!

Content: 
I think the images should be consistent throughout the site, for example having the width and height be set the same.
*It might be easier if you decide what dimensions you want for all pictures and crop it before uploading it into html so none of the photos get weirdly stretched out*

I would also like to see a sentence or two tying in what Korean Food means to you. WHO is Tony?

Technical:
On your sitemap, the "Introduction and Objective" link is not valid (probably forgot to update it as you added more pages), I think href = "index.html" .

On the contact/feedback page, the clear button does not seem to work, I think this is because the type="clear" but it should be "reset"

**Comment by kth1207** [comment]
Thanks for the feedback!!
